version: "3"

services:
  server:
    image: gitea/gitea:1.22.5@sha256:f93616d5c50a774a0e94980683636377cb93d9b022ddf6c21264d678e2539298
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    labels:
        net.unraid.docker.icon: "https://docs.gitea.io/images/gitea.png"
    volumes:
      - ${MOUNT_PATH}:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3005:3000"
      # - "222:22"
