version: "3"

services:
  server:
    image: gitea/gitea:1.21.4@sha256:63220de04217fdda2b2025b9b5000dec5995c77a32cbde0fe4962d6f2bad921a
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    labels:
        net.unraid.docker.icon: "https://docs.gitea.io/images/gitea.png"
    volumes:
      - ${MOUNT_PATH}:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3005:3000"
      - "222:22"
