version: "3"

services:
  server:
    image: gitea/gitea:1.22.3@sha256:76f516a1a8c27e8f8e9773639bf337c0176547a2d42a80843e3f2536787341c6
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    labels:
        net.unraid.docker.icon: "https://docs.gitea.io/images/gitea.png"
    volumes:
      - ${MOUNT_PATH}:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3005:3000"
      # - "222:22"
