version: "3"

services:
  server:
    image: gitea/gitea:1.21.5@sha256:a2095ce71c414c0c6a79192f3933e668a595f7fa7706324edd0aa25c8728f00f
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DISABLE_REGISTRATION=true
      - REGISTER_MANUAL_CONFIRM=true
    restart: always
    labels:
        net.unraid.docker.icon: "https://docs.gitea.io/images/gitea.png"
    volumes:
      - ${MOUNT_PATH}:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3005:3000"
      # - "222:22"
