version: "3"

services:
  server:
    image: gitea/gitea:1.21.6@sha256:ac73e0da341f212c68d37f40d9b0410128d3d5937242f2f3d4f40e1b6c388e05
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    labels:
        net.unraid.docker.icon: "https://docs.gitea.io/images/gitea.png"
    volumes:
      - ${MOUNT_PATH}:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3005:3000"
      # - "222:22"
