version: "3"

services:
  server:
    image: gitea/gitea:1.21.1@sha256:cc5f87a719754b472e5e363ab74a37b77d78a73547cccdc1c9d4a9fce810d888
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    labels:
        net.unraid.docker.icon: "https://docs.gitea.io/images/gitea.png"
    volumes:
      - ${MOUNT_PATH}:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3005:3000"
      - "222:22"
