version: "3"

services:
  server:
    image: gitea/gitea:1.21.2@sha256:aec14185c3e5bb4e0e3436f1b1a1a800eb3393587137daf6e39d0891bc64fa2e
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    labels:
        net.unraid.docker.icon: "https://docs.gitea.io/images/gitea.png"
    volumes:
      - ${MOUNT_PATH}:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3005:3000"
      - "222:22"
