version: "3"

services:
  server:
    image: gitea/gitea:1.22.0@sha256:ff5addffde6abf6e57a7def08f45281eab2a86d2ff6cd92ac88ff84263a87547
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    labels:
        net.unraid.docker.icon: "https://docs.gitea.io/images/gitea.png"
    volumes:
      - ${MOUNT_PATH}:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3005:3000"
      # - "222:22"
