version: "3.5"
services:
  nginx:
    restart: always
    image: "jc21/nginx-proxy-manager:latest@sha256:a77c5893d92f899dd09555bcee1e79268d2bef977779b5221a449d75a9fdcf91"
    volumes:
      - ${MOUNT_PATH}/data:/data:rw
      - ${MOUNT_PATH}/letsencrypt:/etc/letsencrypt:rw
      - ${MOUNT_PATH}/logrotate/nginx-proxy-manager:/etc/logrotate.d/nginx-proxy-manager:rw
    ports:
      - "${MANAGE_PORT}:81"
      - "80:80"
      - "443:443"
    environment:
      - DISABLE_IPV6='true'
