version: "3.5"
services:
  nginx:
    restart: always
    image: "jc21/nginx-proxy-manager:latest@sha256:b7168e5f6828cbbd3622fa19965007e4611cf42b5f3c603008377ffd45a4fe00"
    volumes:
      - ${MOUNT_PATH}/data:/data:rw
      - ${MOUNT_PATH}/letsencrypt:/etc/letsencrypt:rw
      - ${MOUNT_PATH}/logrotate/nginx-proxy-manager:/etc/logrotate.d/nginx-proxy-manager:rw
    ports:
      - "${MANAGE_PORT}:81"
      - "80:80"
      - "443:443"
    environment:
      - DISABLE_IPV6='true'
